language: csharp

mono:
  - latest

install:
  - curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh -o ./scripts/obtain/install.sh

# TODO: See if there's a better way of finding all test projects.
# Note that we want to exclude integration tests; currently this is
# performed by the convention of a suffix of .Tests meaning unit tests.
# The Google* part of each line below is to allow us to have other
# files (e.g. README.md) without that intefering.

script:
  - dotnet restore
  - dotnet build src/Google*
  - dotnet build test/Google*
  - dotnet build tools/Google*
  - dotnet build snippets/Google*
  - for project in `find . -name '*.Tests'`; do dotnet test $project; done
