language: csharp

mono:
  - latest

install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade

# TODO: See if there's a better way of finding all test projects.
# Note that we want to exclude integration tests; currently this is
# performed by the convention of a suffix of .Tests meaning unit tests.
script:
  - dnu restore
  - dnu build src/*
  - dnu build demo/*
  - dnu build test/*
  - for project in `find . -name '*.Tests'`; do dnx -p $project test -parallel none; done
