name: Build and test

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-18.04
    env:
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        regex: ["'Google\\.Cloud\\.[A-L].*'", "'Google\\.Cloud\\.[M-Z].*'", "'!Google\\.Cloud'"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        # TODO: Try depth 100. We diff against master, and we don't know
        # how far back that is... there may be a better approach
        fetch-depth: 0
        
    # We need just the .NET Core 2.1 runtime for testing    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    # We build with .NET Core 3.1 SDK
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: |
        # Make sure the master branch is available for diffing.
        git checkout -b master ${{ github.event.before }}
        git checkout -b after ${{ github.event.after }}
        python3 tools/listapis.py apis/apis.json > /dev/null || travis_terminate 1
        touch build_timing_log.txt
        ./build.sh --diff --regex ${{ matrix.regex }}
        ./processbuildtiminglog.sh
        ./build.sh
