name: Detect differences

on: [pull_request]

jobs:

  diff:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        # TODO: Try depth 100. We diff against master, and we don't know
        # how far back that is... there may be a better approach
        fetch-depth: 0
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Detect PR changes
      run: |
        echo "PR Base: ${{ github.base_ref }}"
        echo "PR Head: ${{ github.head_ref }}"
        git checkout -b master ${{ github.base_ref }}
        git checkout -b after ${{ github.head_ref }}
        git diff --name-only master after
        ./detect-pr-changes.sh
